blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>", views.BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create", views.BlogCreateView.as_view(), name="blog_create"),
    path('blog/<int:pk>/update', views.BlogUpdateView.as_view(), name="blog_update"),
    path('blog/<int:pk>/delete', views.BlogDeleteView.as_view(), name="blog_delete"),
]


financeblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profiles_views
#NEW CODE BELOW
from django.contrib.auth import views as auth_views
#NEW CODE ABOVE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('questions/', include('advice.urls')),
    
    # user related paths below
    path('register/', profiles_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="profiles/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="profiles/logout.html"), name="logout"),
    path('profile/<int:pk>', profiles_views.profile, name="profile"),
    path('profile/update', profiles_views.update, name="update"),
    # user related paths above
    #password reset
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="profiles/password_reset.html"), name="password_reset"),
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="profiles/password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name="profiles/password_reset_done.html"), name="password_reset_done"),
    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(template_name="profiles/password_reset_complete.html"), name="password_reset_complete"),
    #password reset
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advice/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Question(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("question_detail", kwargs={'pk': self.pk})

class Advice(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    date_published = models.DateTimeField(default=timezone.now)       

    def __str__(self):
        return f"Advice by {self.author.username}"

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinLengthValidator
content_validator = MinLengthValidator(limit_value=300, message="Content should be at least 300 characters long!")
class Blog(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(validators=[content_validator])
    date_published = models.DateTimeField(default=timezone.now) 
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog_detail", kwargs={'pk': self.pk})

blog/views.py
# finanaceblog/blog/views.py

from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin 
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

class BlogCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Blog
    fields = ['title', 'content']
    success_message  = "Blog Created Successfully!"
    def form_valid(self, form):
        form.instance.author = self.request.user 
        return super().form_valid(form) 


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Blog
    fields = ['title', 'content']
    success_message  = "Blog Updated Successfully!"
    def form_valid(self, form):
        form.instance.author = self.request.user 
        return super().form_valid(form)
    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        else: 
            return False 

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Blog
    success_message  = "Blog Deleted Successfully!"
    success_url = "/"
    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        else: 
            return False 
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(BlogDeleteView, self).delete(request, *args, **kwargs)


class BlogListView(generic.ListView):
    model = Blog
    ordering = ['-date_published']
    paginate_by = 3


class BlogDetailView(generic.DetailView):
    model = Blog

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <title>My Finance Blog</title>
  </head>
  <body class="bg-light">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
              <a class="navbar-brand mb-0 h1" href="{% url 'blog_list' %}">My Financial Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item ml-2">
              <a href="{% url 'question_create' %}" class="nav-link btn btn-light text-dark">Ask Question</a>
          </li>
            <li class="nav-item ml-2">
              <a href="{% url 'blog_create' %}" class="nav-link btn btn-dark">Write a Blog</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              
              <li class="nav-item">
                  <a href="{% url 'profile' request.user.pk %}" class="nav-link">Profile</a>
              </li>
              <li class="nav-item">
                  <a href="{% url 'logout' %}" class="nav-link">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a href="{% url 'login' %}" class="nav-link">Login</a>
              </li>
              <li class="nav-item">
                  <a href="{% url 'register' %}" class="nav-link">Register</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a href="{% url 'question_list' %}" class="nav-link">Browse Questions</a>
            </li>
          </ul>
          </div>
          </div>
        </nav>
  </header>


{% block content %}

{% endblock content %}


{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show custom-alert" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>

    {% block js %}
    {% endblock js %}

  </body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container bg-light p-5 mt-5 rounded ">
    <div class="row">
        <div class="col-12">
          <h2>Are you sure you want to delete the blog "<strong>{{object.title}}</strong>"?</h2>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <button class="btn btn-danger">Yes please.</button>
                    <a class="btn btn-info" href="{% url 'blog_detail' object.pk %}">No, take me back</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container blog bg-light p-5 mt-5 rounded ">
    <div class="row">
        <div class="col-3 text-center">
          <a class="mugshot-container mb-1" href="{% url 'profile' blog.author.pk %}">
            <div class="mugshot-img mb-2" style="background-image:url({{blog.author.profile.image.url}})"></div>
            <span>{{blog.author.username}}</span>
        </a>
          <small class="text-muted">{{blog.date_published|date:"d/m/Y h:i a"}}</small>
        </div>
        <div class="col-9 question-information pb-1">
          <h1 class="blog-card-title mb-3 font-weight-bold">{{blog.title}}</h1>
          {% if request.user == blog.author %}
            <a href="{% url 'blog_update' blog.pk %}" class="btn btn-sm btn-primary"> Update</a>
            <a href="{% url 'blog_delete' blog.pk %}" class="btn btn-sm btn-danger"> Delete</a>
          {% endif %}
        </div>
    </div>
    <div class="row">
      <div class="col-12 mt-5">
        <p class="line-height text-justify"> {{blog.content}}</p>
      </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/blog_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="landing bg-dark">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12 col-lg-6 text-center">
                <h1 class="text-white font-weight-bold display-3 mb-3">Blog</h1>
            </div>
        </div>
    </div>
</div>
<div class="container bg-light mt-n5 p-5 rounded ">
    <div class="row">
        <div class="col-12">
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="form-group">
                    <button class="btn btn-outline-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends "blog/base.html" %}
{% block content %}
<div class="landing bg-dark">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12 col-lg-6 text-center">
                <h1 class="text-white font-weight-bold display-3 mb-3">Finance blogs to help you succeed.</h1>
            </div>
        </div>
    </div>
</div>
<div class="container p-5 rounded ">
    {% if object_list.count > 0 %}
    {% for blog in object_list %}
        <div class="row blog mb-5">
            <div class="col-lg-2 col-sm-12 text-center">
                <a class="mugshot-container mb-1" href="{% url 'profile' blog.author.pk %}">
                    <div class="mugshot-img mb-2" style="background-image:url({{blog.author.profile.image.url}})"></div>
                    <span>{{blog.author.username}}</span>
                </a>
                <small class="text-muted">{{blog.date_published|date:"d/m/Y h:i a"}}</small>
            </div>
            <div class="col-lg-10 col-sm-12">
                <div class="blog-information">
                    <h1 class="font-weight-bold mb-3">{{blog.title}}</h1>
                    <p>{{blog.content|truncatewords:30}}</p>
                    <a href="{% url 'blog_detail' blog.pk %}" class="font-weight-bold mb-3 d-inline-block">
                        Read More
                    </a>
                    <div class="update-edit">
                        {% if request.user.is_authenticated and request.user == blog.author  %}
                        <a class="btn btn-sm btn-info" href="{% url 'blog_update' blog.pk %}">Update</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'blog_delete' blog.pk %}">Delete</a>
                        {% endif %}
                    </div>    
                </div>
            </div>
        </div>
    {% endfor %}
        <div class="pagination">
            <span class="step-links">
            {% if page_obj.has_previous %}
                <div class="step-divider">
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                </div>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <div class="step-divider">
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                </div>
            {% endif %}
            </span>
        </div>
    {% else %}
        <h2 class="text-muted text-center">It's pretty lonely to have no blogs on a blogging site</h2>
        <p class="mt-3 h3 text-muted text-center">Add a blog? <a href="{% url 'blog_create' %}">Click here</a></p>
    {% endif %}
</div>
{% endblock content %}